Add support for custom resource names
aquasecurity/terraform-gcp-onboarding pull request #14
Opened 2024-08-18 09:25 UTC by Noamstrauss

feat: Add support for custom resource names

- Implement custom naming for `firewall` `network`
- Update the `aqua_gcp_projects_attachment` module with new variables
- Add validation for variables
- Update examples and README with instructions for custom resource names
- Implement tflint for code quality checks

2024-08-18 09:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/terraform-gcp-onboarding?pullRequest=14) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/terraform-gcp-onboarding?pullRequest=14) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: Noamstrauss<br/>:x: github-actions[bot]<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/terraform-gcp-onboarding?pullRequest=14) it.</sub>

2024-08-21 11:50 UTC, nuritbielorai requested changes

2024-08-21 11:50 UTC, nuritbielorai commented on README.md
> +## Resource Naming Customization
Customizing resource names

2024-08-21 11:50 UTC, nuritbielorai commented on README.md
> +This module allows you to customize the names of various resources, ensuring alignment with your organization's naming conventions.
the names of various **resources / variables**

2024-08-21 11:50 UTC, nuritbielorai commented on README.md
> +Before setting custom names, please ensure they comply with each resource's specific naming policies and constraints.
policies and constraints **as defined by GCP. To read more about naming conventions and standards, [please see GCP documentation](https://cloud.google.com/compute/docs/naming-resources)**

2024-08-26 13:49 UTC, danielv-aqua approved these changes

2024-08-27 11:16 UTC, merged