Adding support for organization onboarding
aquasecurity/terraform-gcp-onboarding pull request #7
Opened 2024-05-19 14:40 UTC by Noamstrauss

feat: Adding support for organization onboarding
- Implemented dedicated and same onboarding process
- Updated examples to include organization onboarding
- Updated README with instructions for organization onboarding
- Added `cspm_iam` module for organization - same deployment methods

2024-05-19 14:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/terraform-gcp-onboarding?pullRequest=7) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/terraform-gcp-onboarding?pullRequest=7) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: Noamstrauss<br/>:x: github-actions[bot]<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/terraform-gcp-onboarding?pullRequest=7) it.</sub>

2024-05-20 06:35 UTC, nuritbielorai requested changes
Sent feedback over teams

2024-05-20 08:41 UTC, nuritbielorai approved these changes

2024-05-20 12:18 UTC, iliasokolovski192 approved these changes

2024-05-20 12:30 UTC, merged